[build]
  publish = "."

[[redirects]]
  from = "/app"
  to = "/"
  status = 301

[[redirects]]
  from = "/app/*"
  to = "/:splat"
  status = 301

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=300"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sketches/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
